OPENDJ-1369 Exception (NoClassDefFoundError) when deploying the DSML gateway
Issue caused by r10492 which added opendj-core.jar as a dependency for opendj server.

build.xml:
Added opendj-core.jar to dsml war.